### ISSUE TITLE
Could not set ACL to allow access to IE EPM or Edge.

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/edge-diagnostics-adapter#19]
Hmm, I don't seem to be able to make it work, while the HTTP API works I cannot connect to the WebSocket. Here's what I tried:

1. start Edge;
2. start EdgeDiagnosticsAdapter.exe:

```
Edge Diagnostics Adapter
Could not set ACL to allow access to IE EPM or Edge.
Error Code: 1332
You can set the ACL manually by adding Read & Execute permissions for 'All APPLICATION PACAKGES' to each dll.
Proxy server listening on port 9222...
```

3. start chrome-repl and EdgeDiagnosticsAdapter.exe prints:

```
DEBUG MESSAGE: Attempting to attach to 64 bit tab
Connection rejected for: /devtools/page/E8A36086-8AFC-4300-AC94-8322FB2DC812
[2016-04-24 20:01:41] [error] Handshake ended with HTTP error: 400
```

I'm trying this in a (64 bit) VM. I get similar results with a 32 bit laptop, the difference is that here I don't get the DEBUG MESSAGE: Attempting to attach to 64 bit tab message.

**Comment by andysterland** [comment]
Hmmm. Honestly not sure what happened here. I believe that error code basically means it couldn't find the builtin name  'ALL APPLICATION PACKAGES' [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681385(v=vs.85).aspx). But that name should exsist on Win10 (and down to windows 8). If you:

1. Find the `proxy.dll` and `proxy64.dll`
2. Right click on the dll and `properties`
3. Go to the `Security` panel 
4. `Edit`
5. `Add..`
6. Make sure you have the location to your local machine name (and not a domain etc.)
7. Search for `ALL APPLICATION PACKAGES` (type it in the box)
8. `Check Names` this should resolve the name and underline it (if this fails we have a problem!)
9. `Ok` `OK`, `OK`
10. Now try it... 

Fwiw and this is probably unrelated but the binaries should be somewhere local and not ran from a share.

**Comment by auchenberg** [comment]
This happend to this guy https://github.com/cyrus-and/chrome-remote-interface/issues/21

**Comment by cyrus-and** [comment]
@andysterland thanks, I'll try this ASAP.

**Comment by cyrus-and** [comment]
@andysterland Great, it works now!

But I had to use "TUTTI I PACCHETTI APPLICAZIONI" as my Windows is in Italian.

The error (message) persists though, I think because the adapter checks the [non localized name][1]:

    ea.Trustee.ptstrName = L"ALL APPLICATION PACKAGES";

But it's just shameless speculation...

[1]: https://github.com/Microsoft/edge-diagnostics-adapter/blob/c6673c2ae0ef4a4436a8e18352b02a9525b7f193/EdgeDiagnosticsAdapter/main.cpp#L59

**Comment by andysterland** [comment]
@cyrus-and awesome! And thanks for looking at the code :). I must admit I've never tested in on a non English machine :(. I didn't realize the name was localized though I should have known better. On the pluis side I think the fix is just to use the SID S-1-15-2-1 instead as I'm pretty sure they don't get localized :).

**Comment by cyrus-and** [comment]
@andysterland you're welcome!

> On the pluis side I think the fix is just to use the SID S-1-15-2-1 instead as I'm pretty sure they don't get localized :).

I have no idea... but if I try to do the above with "S-1-15-2-1" it doesn't work: the name cannot be found.

Here's the list of all the possible choices that I have, maybe you might find it useful.

![security_entities](https://cloud.githubusercontent.com/assets/1660263/14864665/2be105f2-0cbb-11e6-8487-7e779f3fa477.png)

**Comment by andysterland** [comment]
Ah yea the SID I'll have to resolve to something in code. I think the change at:
https://github.com/Microsoft/edge-diagnostics-adapter/compare/fixIssue19?expand=1 
I've uploaded an exe that isn't signed if you wanted to quickly test the fix:
https://onedrive.live.com/?id=65B2C5B13821FAB%21375901&cid=065B2C5B13821FAB 
Just getting a non-English VM spun up to test it here.

**Comment by cyrus-and** [comment]
@andysterland unfortunately I don't have a Microsoft account so I cannot open that link, but if you find another way to provide me that file I'd be happy to give it a try.

**Comment by andysterland** [comment]
@cyrus-and sorry, it was marked as public which I guess isn't the same as anonymous. Try: https://1drv.ms/f/s!AqsfghNbLFsGlvhd9AV4QU15xSXPOA

**Comment by cyrus-and** [comment]
@andysterland yup the error massage is gone now, here's what I get:

```
Edge Diagnostics Adapter
Proxy server listening on port 9222...
DEBUG MESSAGE: Attempting to attach to 64 bit tab
Client connection accepted for: /devtools/page/719BDAE6-1843-46E5-BCF3-26FD64DB947B as: 000000000001032A
```

**Comment by auchenberg** [comment]
@cyrus-and .. and does it work? ;)

**Comment by cyrus-and** [comment]
@auchenberg yes it already worked after manually adding the security entities to the DLLs, I thought it was implicit. :)

Anyway yes, it also work with the original DLLs; after the execution the security entities are there.

P.S. I'm having some issues with the chrome-remote-interface but they are not related to this.
