### ISSUE TITLE
Remove Output folder

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/edge-diagnostics-adapter#23]
Added by accident? https://github.com/Microsoft/edge-diagnostics-adapter/tree/master/Output

**Comment by andysterland** [comment]
Whoops that was added by mistake :(. I created it temporally to copy the files somewhere. D'oh:(. Deleted with change https://github.com/Microsoft/edge-diagnostics-adapter/commit/2c875140f5c43933953d030588273922c198f04c
