### ISSUE TITLE
Pressing Ctrl+C should kill the adapter

### ISSUE THREAD

**Issue by nojvek** [Microsoft/edge-diagnostics-adapter#32]
Instead it doing something with packagedebug settings.

Edge Diagnostics Adapter
Proxy server listening on port 9222...
Client connection accepted for: /devtools/page/72C7201E-AB65-40C7-97BD-8FC2723D19DD as: 001C0B3A
Failed to CoCreateInstance of CLSID_PackageDebugSettings.
HR Code: -2147221008
Failed to CoCreateInstance of CLSID_PackageDebugSettings.

**Comment by nojvek** [comment]
This doesn't seem to repro now. Seems its fixed.

**Comment by DanielRuf** [comment]
I am still seeing this message with the latest binary.
