### ISSUE TITLE
NPM distribution is broken due to removed files-attribute in package.json

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/edge-diagnostics-adapter#47]
NPM publishing is currently broken due to the removed files-attribute in the `package.json`.

Broken in https://github.com/Microsoft/edge-diagnostics-adapter/commit/e91e4d9b0cf91968163db4b8ac11468a021457e1

**Comment by molant** [comment]
Fixed via https://github.com/Microsoft/edge-diagnostics-adapter/commit/41cb47cb1c821ea2464c9b4da1b45fb9a5ba33bc

Next release on npm will use `node-pre-gyp` so this shouldn't happen again.

**Comment by auchenberg** [comment]
👍
