### ISSUE TITLE
Build Addon using VS2017

### ISSUE THREAD

**Issue by eiximenis** [Microsoft/edge-diagnostics-adapter#56]
Just opening this issue for reference and keeping work on that :)

I've tried to build the project using `gulp build --x64` with a Windows 10 having only VS2017 installed.
In the VS2017 installer the C++ workload ("Desktop Development with C++") was installed with both C++ toolsets: 141 (VS2017) and 140 (VS2015).

Using `gulp build --x64` failed due to not founding `msbuild`. This can be solved by editing `gulpfile.js` and forcing `toolsVersion` to `15` in the `msbuild` call.
But node-gyp complains about compiling the addin node later.

Tried several things with no luck.

Finally I installed "Visual C++ Tools for VS2015" (http://landinghub.visualstudio.com/visual-cpp-build-tools) and reverting the `toolsVersion` to `14` in the gulpfile.js.
Some errors happening complaining about the file `Microsoft.Cpp.Defaults.props`. Finally need to set these two environment variables:

```
set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140
set GYP_MSVS_VERSION=2015
```

This allowed the compilation of the project using Visual C++ 2015 Tools installed.

Real problem is node-gyp (`gulp-msbuild` works OK with VS2017): i could not make it work with having only VS2017 installed (even though i installed the 14.0 toolset).

I'll do some tests in the future and I'll update the status of this issue. :)
If anyone has any comment about building the project with VS2017 would be very appreciated.

**Comment by eiximenis** [comment]
Hi.

I was able to build with VS2017 by doing two things:

1. Installing the VS2015 cpp tools (http://landinghub.visualstudio.com/visual-cpp-build-tools) 
2. Then setting some environment variables:

```
set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140
set GYP_MSVS_VERSION=2015
```

This is the best way I found :)

**Comment by molant** [comment]
Fixed via https://github.com/Microsoft/edge-diagnostics-adapter/commit/41cb47cb1c821ea2464c9b4da1b45fb9a5ba33bc
