### ISSUE TITLE
Roadmap, project support and uses.

### ISSUE THREAD

**Issue by pedro93** [Microsoft/edge-diagnostics-adapter#57]
Hello,

I just came across this repository and was wondering what the roadmap for this project is and how much active support it has. From the github pulse, not that much. 

I'm particularly interested to know if the purpose of this project is to make Edge have full compatability with the Chrome debugging protocol and how this project can be used in popular projects such as [Lighthouse](https://github.com/GoogleChrome/lighthouse).

**Comment by molant** [comment]
Hi @pedro93,

there has been some investment recently to add new features and update the current infrastructure. You can check https://github.com/Microsoft/edge-diagnostics-adapter/pull/65 and https://github.com/Microsoft/edge-diagnostics-adapter/pull/61 (the readme.md in #65 will tell you all the new stuff coming).

Most of the work in the last PRs has been done to support https://github.com/sonarwhal/sonar.

At this moment, there are no plans to have full compatibility with the Chrome debugging protocol at this moment although there are some Lighthouse tests that might work (but none of the performance ones).

Hope this answers your question!
