### ISSUE TITLE
Fails to attach to 64 bit tabs by returning HTTP 400 on WS connections

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/edge-diagnostics-adapter#59]
**Steps:**
1. Install vscode-edge-debug
2. Start Edge adapter
3. Try to connect VS Code

Windows version: 10.0.15063 Build 15063

<img width="922" alt="screen shot 2017-06-05 at 2 27 30 pm" src="https://cloud.githubusercontent.com/assets/173559/26804048/7725f0c6-49fb-11e7-8bdb-c60c573e281f.png">

**Comment by configurator** [comment]
I'm getting the same issue myself. This happens whether I run `dist/x86/EdgeDiagnosticsAdapter.exe` or `dist/x64/EdgeDiagnosticsAdapter.exe`.

I'm using the latest version on npm, which is currently `0.3.2`.

I'm connecting using Chrome v58.0.3029.110.

**Comment by ivan-zakharchuk** [comment]
the same on x86

**Comment by raphaelstary** [comment]
same issue :(

**Comment by jacobrossi** [comment]
We're working on native support for a CDP-like protocol in Edge that will replace the Edge Diagnostics Adapter. I expect preview builds of basic debugger domain support (and a few other associated APIs) before the end of the year. We're also *hoping* to deliver better support for command-line launching of Edge, which should also make the Edge Diagnostics Launch project defunct as well.  Given that, I don't expect we will be fixing EDA in the meantime. Watch the [Edge blog](https://blog.microsoftedge.com) for more.
