### ISSUE TITLE
New NPM release?

### ISSUE THREAD

**Issue by paulirish** [Microsoft/edge-diagnostics-adapter#63]
I think @molant mentioned some tricky things regarding signing.... but it'd be awesome to have a new release published on NPM when ya'll get a chance. :)

**Comment by molant** [comment]
Hi @paulirish 

Trying to figure out the best way to release this. The current issues we have are:

* Need to have the latest VC++ redistributable installed in the machine.
* Need admin privileges to run it

We are looking at different options to make the user experience smoother.

Thanks!

**Comment by molant** [comment]
[Version 0.6.0 is now available!](https://www.npmjs.com/package/edge-diagnostics-adapter)
